# Generated by Django 6.0 on 2025-12-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('RNC', 'RNC'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_contribuyente', models.CharField(choices=[('JURIDICA', 'Persona Jurídica'), ('FISICA', 'Persona Física'), ('INFORMAL', 'Proveedor Informal'), ('ESTATAL', 'Gobierno / Estatal'), ('EXTRANJERO', 'Extranjero')], default='JURIDICA', help_text='Determina las reglas de retención (DGII)', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('es_internacional', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
