# Generated by Django 6.0 on 2025-12-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'numero_identificacion')},
        ),
    ]
