# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('proveedores', '0003_add_empresa_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('JURIDICA', 'Persona Jurídica'), ('FISICA', 'Persona Física'), ('INFORMAL', 'Proveedor Informal'), ('ESTATAL', 'Gobierno / Estatal'), ('EXTRANJERO', 'Extranjero')], db_index=True, default='JURIDICA', help_text='Determina las reglas de retención (DGII)', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('RNC', 'RNC'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'activo'], name='proveedores_empresa_5c6a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'tipo_identificacion', 'numero_identificacion'], name='proveedores_empresa_ddccc7_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['tipo_contribuyente', 'activo'], name='proveedores_tipo_co_e44f15_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['-fecha_creacion'], name='proveedores_fecha_c_a00f77_idx'),
        ),
    ]
