# Generated by Django 5.2.7 on 2025-12-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_add_permissions'),
        ('proveedores', '0004_alter_proveedor_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'permissions': [('gestionar_proveedor', 'Puede gestionar proveedores')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_tipo_co_e44f15_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_fecha_c_a00f77_idx',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria del proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'tipo_contribuyente', 'activo'], name='proveedores_empresa_9d4e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', '-fecha_creacion'], name='proveedores_empresa_659706_idx'),
        ),
    ]
