# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_categoriacliente_options_and_more'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('productos', '0002_alter_categoria_activa_alter_producto_activo_and_more'),
        ('ventas', '0002_add_empresa_and_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacioncliente',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='devolucionventa',
            options={'ordering': ['-fecha'], 'verbose_name': 'Devolución de Venta', 'verbose_name_plural': 'Devoluciones de Venta'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='listaesperaproducto',
            options={'ordering': ['-fecha_solicitud', 'prioridad'], 'verbose_name': 'Lista de Espera', 'verbose_name_plural': 'Listas de Espera'},
        ),
        migrations.AlterModelOptions(
            name='notacredito',
            options={'ordering': ['-fecha'], 'verbose_name': 'Nota de Crédito', 'verbose_name_plural': 'Notas de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='notadebito',
            options={'ordering': ['-fecha'], 'verbose_name': 'Nota de Débito', 'verbose_name_plural': 'Notas de Débito'},
        ),
        migrations.AlterModelOptions(
            name='pagocaja',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago en Caja', 'verbose_name_plural': 'Pagos en Caja'},
        ),
        migrations.RenameIndex(
            model_name='cotizacioncliente',
            new_name='ventas_coti_empresa_2e6a0b_idx',
            old_name='ventas_coti_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacioncliente',
            new_name='ventas_coti_cliente_6d086f_idx',
            old_name='ventas_coti_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacioncliente',
            new_name='ventas_coti_fecha_bb340e_idx',
            old_name='ventas_coti_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventas_fact_empresa_6746f4_idx',
            old_name='ventas_fact_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventas_fact_cliente_711b7b_idx',
            old_name='ventas_fact_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventas_fact_empresa_83f814_idx',
            old_name='ventas_fact_emp_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventas_fact_numero__b8c200_idx',
            old_name='ventas_fact_num_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocaja',
            new_name='ventas_pago_empresa_cc55bc_idx',
            old_name='ventas_pago_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocaja',
            new_name='ventas_pago_cliente_064aec_idx',
            old_name='ventas_pago_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocaja',
            new_name='ventas_pago_metodo__d1b879_idx',
            old_name='ventas_pago_metodo_idx',
        ),
        migrations.AlterField(
            model_name='cotizacioncliente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADA_PARCIAL', 'Pagada Parcialmente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE_PAGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(db_index=True, help_text='Secuencia interna única', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_venta',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], db_index=True, default='CONTADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='listaesperaproducto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADO', 'Notificado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='listaesperaproducto',
            name='prioridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta')], db_index=True, default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='aplicada',
            field=models.BooleanField(db_index=True, default=False, help_text='Si ya se aplicó al saldo'),
        ),
        migrations.AlterField(
            model_name='pagocaja',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='detallecotizacion',
            index=models.Index(fields=['cotizacion', 'producto'], name='ventas_deta_cotizac_442188_idx'),
        ),
        migrations.AddIndex(
            model_name='detalledevolucion',
            index=models.Index(fields=['devolucion', 'producto'], name='ventas_deta_devoluc_ac0cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefactura',
            index=models.Index(fields=['factura', 'producto'], name='ventas_deta_factura_41951b_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['empresa', 'fecha'], name='ventas_devo_empresa_60e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['cliente', 'fecha'], name='ventas_devo_cliente_298404_idx'),
        ),
        migrations.AddIndex(
            model_name='listaesperaproducto',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_list_empresa_92683f_idx'),
        ),
        migrations.AddIndex(
            model_name='listaesperaproducto',
            index=models.Index(fields=['producto', 'estado'], name='ventas_list_product_83e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='listaesperaproducto',
            index=models.Index(fields=['prioridad', '-fecha_solicitud'], name='ventas_list_priorid_049d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['empresa', 'fecha'], name='ventas_nota_empresa_3fe0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['cliente', 'aplicada'], name='ventas_nota_cliente_f27eba_idx'),
        ),
        migrations.AddIndex(
            model_name='notadebito',
            index=models.Index(fields=['empresa', 'fecha'], name='ventas_nota_empresa_87ceee_idx'),
        ),
        migrations.AddIndex(
            model_name='notadebito',
            index=models.Index(fields=['cliente', 'fecha'], name='ventas_nota_cliente_0c73b0_idx'),
        ),
    ]
