# Generated by Django 6.0 - Fixed for GeneratedField

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cotizacioncliente_options_and_more'),
    ]

    operations = [
        # Step 1: Remove the old field
        migrations.RemoveField(
            model_name='detallefactura',
            name='importe',
        ),
        # Step 2: Add the new GeneratedField
        migrations.AddField(
            model_name='detallefactura',
            name='importe',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            models.F('cantidad'), '*', models.F('precio_unitario')
                        ),
                        '-', models.F('descuento')
                    ),
                    '+', models.F('itbis')
                ),
                help_text='Importe total (calculado automáticamente)',
                output_field=models.DecimalField(decimal_places=2, max_digits=12)
            ),
        ),
    ]
