# Generated by Django 6.0 on 2025-12-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(help_text='Código de etiqueta / Placa de inventario', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, help_text='Serial, VIN, Chasis, etc.', max_length=100, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Oficina, Planta, Almacén X', max_length=200, null=True)),
                ('fecha_adquisicion', models.DateField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_libro_actual', models.DecimalField(decimal_places=2, help_text='Valor tras depreciación acumulada', max_digits=14)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo / En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DEPRECIADO', 'Totalmente Depreciado'), ('VENDIDO', 'Vendido'), ('DESINCORPORADO', 'Desincorporado / Dañado')], default='ACTIVO', max_length=20)),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Detalles técnicos adicionales (Color, Motor, Capacidad, etc.)')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
            },
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_libro_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_libro_nuevo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Depreciación',
                'verbose_name_plural': 'Depreciaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_depreciacion_anual', models.DecimalField(decimal_places=2, help_text='Porcentaje de depreciación fiscal anual (ej. 25.00 para vehículos)', max_digits=5)),
                ('vida_util_anos', models.IntegerField(help_text='Vida útil estimada en años')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activo',
            },
        ),
    ]
