# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='compra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_generados', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='detalle_compra_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_fijo_generado', to='compras.detallecompra'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='producto_origen',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo base', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
