# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciacion',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='activos.activofijo'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoactivo',
            unique_together={('nombre',)},
        ),
        migrations.AddField(
            model_name='activofijo',
            name='tipo_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.tipoactivo'),
        ),
        migrations.AlterUniqueTogether(
            name='activofijo',
            unique_together={('codigo_interno',)},
        ),
    ]
