# Generated by Django 5.2.7 on 2025-12-17 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_add_empresa_and_audit_fields'),
        ('productos', '0004_rename_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles tecnicos adicionales (Color, Motor, Capacidad, etc.)'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='producto_origen',
            field=models.ForeignKey(blank=True, help_text='Producto del catalogo base', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Oficina, Planta, Almacen X', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='valor_libro_actual',
            field=models.DecimalField(decimal_places=2, help_text='Valor tras depreciacion acumulada', max_digits=14),
        ),
        migrations.AlterField(
            model_name='tipoactivo',
            name='porcentaje_depreciacion_anual',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de depreciacion fiscal anual (ej. 25.00 para vehiculos)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipoactivo',
            name='vida_util_anos',
            field=models.IntegerField(help_text='Vida util estimada en anos'),
        ),
    ]
