# Generated by Django 6.0 on 2025-12-18 01:21

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='depreciacion_acumulada',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('valor_adquisicion'), '-', models.F('valor_libro_actual')), help_text='Depreciación acumulada (calculado automáticamente)', output_field=models.DecimalField(decimal_places=2, max_digits=14)),
        ),
    ]
