# Generated by Django 5.2.7 on 2025-12-18 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activofijo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('depreciar_activofijo', 'Puede registrar depreciaciones de activos'), ('cambiar_estado_activofijo', 'Puede cambiar el estado de activos'), ('ver_proyeccion_activofijo', 'Puede ver proyecciones de depreciación')], 'verbose_name': 'Activo Fijo', 'verbose_name_plural': 'Activos Fijos'},
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depreciacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
