# Generated by Django 5.2.7 on 2025-12-16 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_categoriacliente_options_and_more'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('ventas', '0003_alter_cotizacioncliente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_cobro', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Numero de transferencia, cheque, etc.', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_clientes', to='empresas.empresa')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobro de Cliente',
                'verbose_name_plural': 'Cobros de Clientes',
                'ordering': ['-fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(db_index=True, help_text='Numero de factura', max_length=50)),
                ('fecha_documento', models.DateField(help_text='Fecha de la factura')),
                ('fecha_vencimiento', models.DateField(db_index=True, help_text='Fecha limite de cobro')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Monto total de la factura', max_digits=14)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, help_text='Saldo pendiente', max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Cobro Parcial'), ('COBRADA', 'Cobrada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='empresas.empresa')),
                ('factura', models.OneToOneField(help_text='Factura de venta origen', on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='ventas.factura')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxc_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxc_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCobroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cuentas_cobrar.cobrocliente')),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_aplicados', to='cuentas_cobrar.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Detalle de Cobro a Cliente',
                'verbose_name_plural': 'Detalles de Cobro a Cliente',
            },
        ),
        migrations.AddIndex(
            model_name='cobrocliente',
            index=models.Index(fields=['empresa', 'fecha_cobro'], name='cuentas_cob_empresa_a9f148_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrocliente',
            index=models.Index(fields=['cliente', 'fecha_cobro'], name='cuentas_cob_cliente_d3900a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['empresa', 'estado'], name='cuentas_cob_empresa_a99824_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['cliente', 'estado'], name='cuentas_cob_cliente_b72f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='cuentas_cob_empresa_acb867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecobrocliente',
            unique_together={('cobro', 'cuenta_por_cobrar')},
        ),
    ]
