# Generated by Django 5.2.7 on 2025-12-18 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_cobrar', '0003_alter_cuentaporcobrar_monto_pendiente'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecobrocliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cobros_clientes', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='detallecobrocliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecobrocliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecobrocliente',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cobros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecobrocliente',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cobros_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecobrocliente',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='detallecobrocliente',
            index=models.Index(fields=['empresa', 'cobro'], name='cuentas_cob_empresa_d1851f_idx'),
        ),
    ]
