# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('vendedores', '0002_add_empresa_and_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['empresa', 'activo'], name='vendedores__empresa_dd3cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['empresa', 'cedula'], name='vendedores__empresa_e32920_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['-fecha_creacion'], name='vendedores__fecha_c_dc9d33_idx'),
        ),
    ]
