# Generated by Django 5.2.7 on 2025-12-16 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0005_alter_compra_options_alter_gasto_options_and_more'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('proveedores', '0004_alter_proveedor_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(db_index=True, help_text='Numero de factura del proveedor', max_length=50)),
                ('fecha_documento', models.DateField(help_text='Fecha de la factura')),
                ('fecha_vencimiento', models.DateField(db_index=True, help_text='Fecha limite de pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Monto total de la factura', max_digits=14)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, help_text='Saldo pendiente', max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('compra', models.OneToOneField(help_text='Factura de compra origen', on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='compras.compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='empresas.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='proveedores.proveedor')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_pago', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Numero de transferencia, cheque, etc.', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedores', to='empresas.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='proveedores.proveedor')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DetallePagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_aplicados', to='cuentas_pagar.cuentaporpagar')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cuentas_pagar.pagoproveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Pago a Proveedor',
                'verbose_name_plural': 'Detalles de Pago a Proveedor',
            },
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['empresa', 'estado'], name='cuentas_pag_empresa_3b0def_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['proveedor', 'estado'], name='cuentas_pag_proveed_86fd12_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='cuentas_pag_empresa_72a2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['empresa', 'fecha_pago'], name='cuentas_pag_empresa_bac76d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['proveedor', 'fecha_pago'], name='cuentas_pag_proveed_de231c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepagoproveedor',
            unique_together={('pago', 'cuenta_por_pagar')},
        ),
    ]
