# Generated by Django 6.0 - Fixed for GeneratedField

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_pagar', '0002_pagoproveedor_usuario_modificacion'),
    ]

    operations = [
        # Step 1: Remove the old field
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='monto_pendiente',
        ),
        # Step 2: Add the new GeneratedField
        migrations.AddField(
            model_name='cuentaporpagar',
            name='monto_pendiente',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F('monto_original'), '-', models.F('monto_pagado')
                ),
                help_text='Saldo pendiente (calculado automáticamente)',
                output_field=models.DecimalField(decimal_places=2, max_digits=14)
            ),
        ),
    ]
