# Generated by Django 5.2.7 on 2025-12-18 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_pagar', '0003_alter_cuentaporpagar_monto_pendiente'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pagos_proveedores', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pagos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pagos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepagoproveedor',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_proveedores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_proveedores_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='detallepagoproveedor',
            index=models.Index(fields=['empresa', 'pago'], name='cuentas_pag_empresa_b717e6_idx'),
        ),
    ]
