# Generated by Django 5.2.7 on 2025-12-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_pagar', '0004_add_empresa_audit_to_detalle'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('proveedores', '0004_alter_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentaporpagar',
            unique_together={('empresa', 'proveedor', 'numero_documento')},
        ),
    ]
