# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacliente',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_cliente_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriacliente',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_cliente_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.categoriacliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor_asignado',
            field=models.ForeignKey(blank=True, help_text='Vendedor asignado por defecto a este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='vendedores.vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriacliente',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('numero_identificacion',)},
        ),
    ]
