# Generated by Django 6.0 on 2025-12-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriacliente',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoriacliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_cliente', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriacliente',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'numero_identificacion')},
        ),
    ]
