# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_empresa_fields'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('vendedores', '0003_alter_vendedor_activo_alter_vendedor_cedula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Cliente', 'verbose_name_plural': 'Categorías de Clientes'},
        ),
        migrations.AlterField(
            model_name='categoriacliente',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('RNC', 'RNC'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='categoriacliente',
            index=models.Index(fields=['empresa', 'activa'], name='clientes_ca_empresa_328ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriacliente',
            index=models.Index(fields=['-fecha_creacion'], name='clientes_ca_fecha_c_9a48ac_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'activo'], name='clientes_cl_empresa_8e803f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'tipo_identificacion', 'numero_identificacion'], name='clientes_cl_empresa_62cacb_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['vendedor_asignado', 'activo'], name='clientes_cl_vendedo_4cbd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['-fecha_creacion'], name='clientes_cl_fecha_c_c855cf_idx'),
        ),
    ]
