# Generated by Django 5.2.7 on 2025-12-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_categoriacliente_options_and_more'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresas.empresa'),
        ),
    ]
