# Generated by Django 6.0 on 2025-12-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaNCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Talonario Principal Facturas Crédito Fiscal', max_length=100)),
                ('secuencia_inicial', models.IntegerField(help_text='Número inicial autorizado (ej. 1)')),
                ('secuencia_final', models.IntegerField(help_text='Número final autorizado (ej. 100)')),
                ('secuencia_actual', models.IntegerField(default=0, help_text='Último número utilizado')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la secuencia')),
                ('alerta_cantidad', models.IntegerField(default=10, help_text='Avisar cuando queden X números')),
                ('activo', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secuencia NCF',
                'verbose_name_plural': 'Secuencias NCF',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 01, 02, 11, 14, 15', max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(default='B', help_text='Prefijo de la serie (Generalmente B o E)', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobantes',
                'ordering': ['codigo'],
            },
        ),
    ]
