# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgii', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secuenciancf',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secuencias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuenciancf',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secuencias_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuenciancf',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dgii.tipocomprobante'),
        ),
        migrations.AlterUniqueTogether(
            name='secuenciancf',
            unique_together={('tipo_comprobante', 'secuencia_inicial')},
        ),
    ]
