# Generated by Django 5.2.7 on 2025-12-17 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgii', '0003_add_empresa_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciancf',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secuencias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secuenciancf',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secuencias_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
