# Generated by Django 5.2.7 on 2025-12-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgii', '0004_alter_user_fields'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_comprobante_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_comprobante_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secuenciancf',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True, help_text='Fecha de vencimiento de la secuencia'),
        ),
        migrations.AddIndex(
            model_name='secuenciancf',
            index=models.Index(fields=['empresa', 'tipo_comprobante'], name='dgii_secuen_empresa_cba33c_idx'),
        ),
        migrations.AddIndex(
            model_name='secuenciancf',
            index=models.Index(fields=['empresa', 'activo'], name='dgii_secuen_empresa_314c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='secuenciancf',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='dgii_secuen_empresa_71cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomprobante',
            index=models.Index(fields=['empresa', 'codigo'], name='dgii_tipoco_empresa_586e14_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomprobante',
            index=models.Index(fields=['empresa', 'activo'], name='dgii_tipoco_empresa_a3a8b0_idx'),
        ),
    ]
