# Generated by Django 5.2.7 on 2025-12-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgii', '0005_add_tipocomprobante_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secuenciancf',
            options={'permissions': [('gestionar_secuenciancf', 'Puede gestionar secuencias NCF'), ('generar_secuenciancf', 'Puede generar NCF'), ('generar_reporte_606', 'Puede generar reporte 606 (compras)'), ('generar_reporte_607', 'Puede generar reporte 607 (ventas)'), ('generar_reporte_608', 'Puede generar reporte 608 (anulados)')], 'verbose_name': 'Secuencia NCF', 'verbose_name_plural': 'Secuencias NCF'},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'ordering': ['codigo'], 'permissions': [('gestionar_tipocomprobante', 'Puede gestionar tipos de comprobante')], 'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobantes'},
        ),
    ]
