# Generated by Django 6.0 on 2025-12-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('AJUSTE_INVENTARIO', 'Ajuste de Inventario'), ('AJUSTE_DIFERENCIA', 'Ajuste por Diferencia'), ('AJUSTE_DETERIORO', 'Ajuste por Deterioro'), ('AJUSTE_ROBO', 'Ajuste por Robo/Pérdida'), ('AJUSTE_DONACION', 'Ajuste por Donación'), ('AJUSTE_MUESTRA', 'Ajuste por Muestra'), ('AJUSTE_PRODUCCION', 'Ajuste por Producción'), ('AJUSTE_DESECHO', 'Ajuste por Desecho')], max_length=30)),
                ('motivo', models.TextField()),
                ('fecha_ajuste', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_ajuste'],
            },
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo Mínimo'), ('STOCK_AGOTADO', 'Stock Agotado'), ('VENCIMIENTO_PROXIMO', 'Vencimiento Próximo'), ('VENCIMIENTO_VENCIDO', 'Producto Vencido'), ('STOCK_EXCESIVO', 'Stock Excesivo')], max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conteo', models.CharField(max_length=50, unique=True)),
                ('fecha_conteo', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('AJUSTADO', 'Ajustado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=20)),
                ('tipo_conteo', models.CharField(choices=[('COMPLETO', 'Conteo Completo'), ('CICLICO', 'Conteo Cíclico'), ('SELECTIVO', 'Conteo Selectivo')], default='COMPLETO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-fecha_conteo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_nueva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Calculado automáticamente', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Ajuste',
                'verbose_name_plural': 'Detalles de Ajustes',
            },
        ),
        migrations.CreateModel(
            name='DetalleConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.DecimalField(decimal_places=2, help_text='Cantidad según sistema', max_digits=12)),
                ('cantidad_fisica', models.DecimalField(decimal_places=2, help_text='Cantidad contada físicamente', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Diferencia (Físico - Sistema)', max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Conteo Físico',
                'verbose_name_plural': 'Detalles de Conteos Físicos',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencias',
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('metodo_valoracion', models.CharField(choices=[('PROMEDIO', 'Costo Promedio Ponderado'), ('PEPS', 'Primero en Entrar, Primero en Salir (FIFO)'), ('UEPS', 'Último en Entrar, Primero en Salir (LIFO)'), ('PRECIO_ESPECIFICO', 'Precio Específico')], default='PROMEDIO', help_text='Método de valoración de inventario', max_length=20)),
                ('costo_unitario_actual', models.DecimalField(decimal_places=4, default=0, help_text='Costo unitario actual según método de valoración', max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima antes de alertar', max_digits=12)),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad máxima recomendada', max_digits=12)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, help_text='Punto de reorden automático', max_digits=12)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Inventario de Producto',
                'verbose_name_plural': 'Inventarios de Productos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Código de lote/serie', max_length=100)),
                ('numero_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('BLOQUEADO', 'Bloqueado'), ('VENCIDO', 'Vencido'), ('AGOTADO', 'Agotado')], default='DISPONIBLE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('TRANSFERENCIA_ENTRADA', 'Transferencia (Entrada)'), ('TRANSFERENCIA_SALIDA', 'Transferencia (Salida)'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario'), ('AJUSTE_DIFERENCIA', 'Ajuste por Diferencia'), ('AJUSTE_DETERIORO', 'Ajuste por Deterioro'), ('AJUSTE_ROBO', 'Ajuste por Robo/Pérdida'), ('AJUSTE_DONACION', 'Ajuste por Donación'), ('AJUSTE_MUESTRA', 'Ajuste por Muestra'), ('AJUSTE_PRODUCCION', 'Ajuste por Producción'), ('AJUSTE_DESECHO', 'Ajuste por Desecho')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='ID de Compra, Factura, etc.', max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_lote_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento_origen', models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('FACTURA', 'Factura'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferencia'), ('DEVOLUCION', 'Devolución'), ('CONTEO', 'Conteo Físico')], max_length=50, null=True)),
                ('documento_origen_id', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('referencia', models.CharField(help_text='ID de Cotización, Factura, etc.', max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Reserva de Stock',
                'verbose_name_plural': 'Reservas de Stock',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transferencia', models.CharField(max_length=50, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
