# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='usuario_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='usuario_resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('nombre',)},
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='conteofisico',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='conteofisico',
            name='usuario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleajusteinventario',
            name='ajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ajusteinventario'),
        ),
        migrations.AddField(
            model_name='detalleajusteinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detalleconteofisico',
            name='contado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleconteofisico',
            name='conteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.conteofisico'),
        ),
        migrations.AddField(
            model_name='detalleconteofisico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.inventarioproducto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='lote',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.compra'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='detalleconteofisico',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='detalleajusteinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.inventarioproducto'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='almacen_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferenciainventario'),
        ),
        migrations.AddIndex(
            model_name='inventarioproducto',
            index=models.Index(fields=['producto', 'almacen'], name='inventario__product_3f376a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioproducto',
            index=models.Index(fields=['cantidad_disponible'], name='inventario__cantida_57a85f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together={('producto', 'almacen')},
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_d666fe_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='inventario__estado_538a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['codigo_lote'], name='inventario__codigo__7178c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'almacen', 'codigo_lote')},
        ),
        migrations.AddIndex(
            model_name='alertainventario',
            index=models.Index(fields=['resuelta', '-fecha_alerta'], name='inventario__resuelt_a54da2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertainventario',
            index=models.Index(fields=['tipo', 'resuelta'], name='inventario__tipo_af0395_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'almacen', '-fecha'], name='inventario__product_09e3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', '-fecha'], name='inventario__tipo_mo_7a0763_idx'),
        ),
        migrations.AddIndex(
            model_name='reservastock',
            index=models.Index(fields=['estado', '-fecha_reserva'], name='inventario__estado_8ba5dc_idx'),
        ),
    ]
