# Generated by Django 5.2.7 on 2025-12-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_add_empresa_and_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
