# Generated by Django 6.0 on 2025-12-18 01:18

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='valor_inventario',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cantidad_disponible'), '*', models.F('costo_promedio')), help_text='Valor total del inventario (calculado automáticamente)', output_field=models.DecimalField(decimal_places=2, max_digits=18)),
        ),
    ]
