# Generated by Django 5.2.7 on 2025-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventarioproducto_valor_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
