# Generated by Django 5.2.7 on 2025-12-19 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_rename_indexes'),
        ('empresas', '0003_add_permissions'),
        ('inventario', '0006_alter_inventarioproducto_punto_reorden_and_more'),
        ('productos', '0004_rename_indexes'),
        ('proveedores', '0004_alter_proveedor_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteinventario',
            options={'ordering': ['-fecha_ajuste'], 'permissions': [('gestionar_ajusteinventario', 'Puede gestionar ajustes'), ('aprobar_ajusteinventario', 'Puede aprobar ajustes')], 'verbose_name': 'Ajuste de Inventario', 'verbose_name_plural': 'Ajustes de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='alertainventario',
            options={'ordering': ['-fecha_alerta'], 'permissions': [('gestionar_alertainventario', 'Puede gestionar alertas de inventario')], 'verbose_name': 'Alerta de Inventario', 'verbose_name_plural': 'Alertas de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='almacen',
            options={'permissions': [('gestionar_almacen', 'Puede gestionar almacenes')], 'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='conteofisico',
            options={'ordering': ['-fecha_conteo'], 'permissions': [('gestionar_conteofisico', 'Puede gestionar conteos físicos')], 'verbose_name': 'Conteo Físico', 'verbose_name_plural': 'Conteos Físicos'},
        ),
        migrations.AlterModelOptions(
            name='inventarioproducto',
            options={'permissions': [('gestionar_inventarioproducto', 'Puede gestionar inventario')], 'verbose_name': 'Inventario de Producto', 'verbose_name_plural': 'Inventarios de Productos'},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'permissions': [('gestionar_lote', 'Puede gestionar lotes')], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'permissions': [('gestionar_movimientoinventario', 'Puede gestionar movimientos'), ('ver_kardex', 'Puede ver Kardex')], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='reservastock',
            options={'ordering': ['-fecha_reserva'], 'permissions': [('gestionar_reservastock', 'Puede gestionar reservas de stock')], 'verbose_name': 'Reserva de Stock', 'verbose_name_plural': 'Reservas de Stock'},
        ),
        migrations.AlterModelOptions(
            name='transferenciainventario',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('gestionar_transferenciainventario', 'Puede gestionar transferencias')], 'verbose_name': 'Transferencia de Inventario', 'verbose_name_plural': 'Transferencias de Inventario'},
        ),
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_113225_idx'),
        ),
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['empresa', '-fecha_ajuste'], name='inventario__empresa_553796_idx'),
        ),
        migrations.AddIndex(
            model_name='alertainventario',
            index=models.Index(fields=['empresa', 'resuelta'], name='inventario__empresa_490cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'activo'], name='inventario__empresa_fb3597_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'nombre'], name='inventario__empresa_39028e_idx'),
        ),
        migrations.AddIndex(
            model_name='conteofisico',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_42bf97_idx'),
        ),
        migrations.AddIndex(
            model_name='conteofisico',
            index=models.Index(fields=['empresa', '-fecha_conteo'], name='inventario__empresa_0bfc3a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioproducto',
            index=models.Index(fields=['empresa', 'almacen'], name='inventario__empresa_78345f_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['empresa', 'producto'], name='inventario__empresa_4e0ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', '-fecha'], name='inventario__empresa_ea53d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservastock',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_32dba3_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_268ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['empresa', '-fecha_solicitud'], name='inventario__empresa_7963ee_idx'),
        ),
    ]
