# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rnc',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activo', 'nombre'], name='empresas_em_activo_2b6b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['-fecha_creacion'], name='empresas_em_fecha_c_91b923_idx'),
        ),
    ]
