# Generated by Django 5.2.7 on 2025-12-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('gestionar_empresa', 'Puede gestionar empresas'), ('actualizar_configuracion_fiscal', 'Puede actualizar configuración fiscal'), ('ver_estadisticas', 'Puede ver estadísticas de empresa')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
