# Generated by Django 6.0 on 2025-12-12 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_producto', models.CharField(choices=[('ALMACENABLE', 'Producto Almacenable (Inventario)'), ('SERVICIO', 'Servicio (Intangible)'), ('CONSUMIBLE', 'Consumible (Uso Interno)'), ('ACTIVO_FIJO', 'Activo Fijo (Maquinaria/Equipos)')], default='ALMACENABLE', help_text='Define cómo se comporta el producto en compras e inventario', max_length=20)),
                ('controlar_stock', models.BooleanField(default=True, help_text='Si es Falso, el sistema no validará existencias (útil para servicios o consumibles directos)')),
                ('precio_venta_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('impuesto_itbis', models.DecimalField(decimal_places=2, default=18.0, help_text='Porcentaje de ITBIS (ej. 18.00). Si es exento, colocar 0.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('es_exento', models.BooleanField(default=False, help_text='Marcar si el producto está legalmente exonerado de ITBIS (ej. Transporte, Libros)')),
                ('tiene_garantia', models.BooleanField(default=False, help_text='Indica si el producto tiene garantía')),
                ('meses_garantia', models.IntegerField(default=0, help_text='Duración de la garantía en meses', validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento_promocional', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento automático aplicado al precio base', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento_maximo', models.DecimalField(decimal_places=2, default=0.0, help_text='Máximo descuento manual permitido a vendedores', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
