# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_sku',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_exento',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcar si el producto está legalmente exonerado de ITBIS (ej. Transporte, Libros)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ALMACENABLE', 'Producto Almacenable (Inventario)'), ('SERVICIO', 'Servicio (Intangible)'), ('CONSUMIBLE', 'Consumible (Uso Interno)'), ('ACTIVO_FIJO', 'Activo Fijo (Maquinaria/Equipos)')], db_index=True, default='ALMACENABLE', help_text='Define cómo se comporta el producto en compras e inventario', max_length=20),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activa', 'nombre'], name='productos_c_activa_c70db8_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'tipo_producto'], name='productos_p_activo_0319d5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_sku', 'activo'], name='productos_p_codigo__c3f480_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-fecha_creacion'], name='productos_p_fecha_c_fb7a00_idx'),
        ),
    ]
