# Generated by Django 5.2.7 on 2025-12-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_add_imagenproducto_referenciascruzadas'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imagenproducto',
            new_name='productos_i_product_5949f2_idx',
            old_name='productos_i_product_8f3a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='imagenproducto',
            new_name='productos_i_product_168eaa_idx',
            old_name='productos_i_product_d7b4e1_idx',
        ),
    ]
