# Generated by Django 5.2 on 2025-12-18
# Migration for adding audit fields and permissions to productos models

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0004_rename_indexes'),
    ]

    operations = [
        # ========== CATEGORIA MODEL ==========
        # Add uuid field
        migrations.AddField(
            model_name='categoria',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Add fecha_creacion field
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Add fecha_actualizacion field
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add usuario_creacion field
        migrations.AddField(
            model_name='categoria',
            name='usuario_creacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='categorias_creadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add usuario_modificacion field
        migrations.AddField(
            model_name='categoria',
            name='usuario_modificacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='categorias_modificadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # ========== PRODUCTO MODEL ==========
        # Add uuid field
        migrations.AddField(
            model_name='producto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Add usuario_creacion field
        migrations.AddField(
            model_name='producto',
            name='usuario_creacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos_creados',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add usuario_modificacion field
        migrations.AddField(
            model_name='producto',
            name='usuario_modificacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos_modificados',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # ========== IMAGENPRODUCTO MODEL ==========
        # Add usuario_creacion field
        migrations.AddField(
            model_name='imagenproducto',
            name='usuario_creacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='imagenes_producto_creadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add usuario_modificacion field
        migrations.AddField(
            model_name='imagenproducto',
            name='usuario_modificacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='imagenes_producto_modificadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # ========== REFERENCIASCRUZADAS MODEL ==========
        # Add fecha_actualizacion field
        migrations.AddField(
            model_name='referenciascruzadas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add usuario_creacion field
        migrations.AddField(
            model_name='referenciascruzadas',
            name='usuario_creacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referencias_creadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add usuario_modificacion field
        migrations.AddField(
            model_name='referenciascruzadas',
            name='usuario_modificacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referencias_modificadas',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # ========== INDEXES ==========
        # Add indexes for ReferenciasCruzadas
        migrations.AddIndex(
            model_name='referenciascruzadas',
            index=models.Index(
                fields=['producto_origen', 'tipo', 'activa'],
                name='productos_r_product_a3b8e1_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='referenciascruzadas',
            index=models.Index(
                fields=['producto_destino', 'bidireccional', 'activa'],
                name='productos_r_product_d2f1c3_idx'
            ),
        ),

        # ========== PERMISSIONS ==========
        # Add custom permissions to Categoria
        migrations.AlterModelOptions(
            name='categoria',
            options={
                'ordering': ['nombre'],
                'permissions': [('gestionar_categoria', 'Puede gestionar categorías')],
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías'
            },
        ),
        # Add custom permissions to Producto
        migrations.AlterModelOptions(
            name='producto',
            options={
                'ordering': ['nombre'],
                'permissions': [
                    ('gestionar_producto', 'Puede gestionar productos'),
                    ('cargar_catalogo', 'Puede cargar catálogo masivo')
                ],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos'
            },
        ),
        # Add custom permissions to ImagenProducto
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={
                'ordering': ['producto', 'orden', '-es_principal'],
                'permissions': [('gestionar_imagenproducto', 'Puede gestionar imágenes de productos')],
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos'
            },
        ),
        # Add custom permissions to ReferenciasCruzadas
        migrations.AlterModelOptions(
            name='referenciascruzadas',
            options={
                'ordering': ['producto_origen', 'tipo'],
                'permissions': [('gestionar_referenciascruzadas', 'Puede gestionar referencias cruzadas')],
                'verbose_name': 'Referencia Cruzada',
                'verbose_name_plural': 'Referencias Cruzadas'
            },
        ),
    ]
