# Generated by Django 5.2.7 on 2025-12-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_add_permissions'),
        ('productos', '0005_add_audit_fields_and_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoria',
            name='productos_c_activa_c70db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagenproducto',
            name='productos_i_product_5949f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagenproducto',
            name='productos_i_product_168eaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_activo_0319d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_codigo__c3f480_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_fecha_c_fb7a00_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenciascruzadas',
            name='productos_r_product_a3b8e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenciascruzadas',
            name='productos_r_product_d2f1c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='referenciascruzadas',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria de la categoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria de la imagen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria del producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='referenciascruzadas',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria de la referencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_producto', to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'codigo_sku')},
        ),
        migrations.AlterUniqueTogether(
            name='referenciascruzadas',
            unique_together={('empresa', 'producto_origen', 'producto_destino', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['empresa', 'activa', 'nombre'], name='productos_c_empresa_704901_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['empresa', 'producto', 'es_principal'], name='productos_i_empresa_554b50_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['empresa', 'producto', 'activa', 'orden'], name='productos_i_empresa_e6bc96_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'tipo_producto'], name='productos_p_empresa_0c2a88_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'codigo_sku'], name='productos_p_empresa_ccefe5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', '-fecha_creacion'], name='productos_p_empresa_a45ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='referenciascruzadas',
            index=models.Index(fields=['empresa', 'producto_origen', 'tipo', 'activa'], name='productos_r_empresa_e60d64_idx'),
        ),
        migrations.AddIndex(
            model_name='referenciascruzadas',
            index=models.Index(fields=['empresa', 'producto_destino', 'bidireccional', 'activa'], name='productos_r_empresa_bd7029_idx'),
        ),
    ]
