# Generated by Django 5.2.7 on 2025-12-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_add_empresa_and_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['nombre'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.RenameIndex(
            model_name='caja',
            new_name='caja_caja_empresa_cab709_idx',
            old_name='caja_caja_empresa_7a8d13_idx',
        ),
        migrations.RenameIndex(
            model_name='caja',
            new_name='caja_caja_empresa_e19de1_idx',
            old_name='caja_caja_empresa_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocaja',
            new_name='caja_movimi_empresa_9e7dfd_idx',
            old_name='caja_movimi_empresa_m1n2o3_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocaja',
            new_name='caja_movimi_empresa_e77e01_idx',
            old_name='caja_movimi_empresa_p4q5r6_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocaja',
            new_name='caja_movimi_sesion__10c3a4_idx',
            old_name='caja_movimi_sesion__s7t8u9_idx',
        ),
        migrations.RenameIndex(
            model_name='sesioncaja',
            new_name='caja_sesion_empresa_787e5a_idx',
            old_name='caja_sesion_empresa_d1e2f3_idx',
        ),
        migrations.RenameIndex(
            model_name='sesioncaja',
            new_name='caja_sesion_empresa_3d2ce2_idx',
            old_name='caja_sesion_empresa_g4h5i6_idx',
        ),
        migrations.RenameIndex(
            model_name='sesioncaja',
            new_name='caja_sesion_caja_id_358370_idx',
            old_name='caja_sesion_caja_id_j7k8l9_idx',
        ),
    ]
