# Generated by Django 6.0 on 2025-12-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('despachos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
