# Generated by Django 5.2.7 on 2025-12-17 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_categoriacliente_options_and_more'),
        ('despachos', '0004_add_empresa_and_audit_fields'),
        ('inventario', '0004_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='clientes.cliente'),
        ),
    ]
