# Generated by Django 6.0 on 2025-12-12 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='empresas.empresa'),
        ),
    ]
