# Generated by Django 5.2.7 on 2025-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('usuarios', '0002_add_empresa_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('facturador', 'Facturador'), ('cajero', 'Cajero'), ('almacen', 'Almacén'), ('compras', 'Compras'), ('contabilidad', 'Contabilidad')], db_index=True, default='facturador', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['empresa', 'rol'], name='usuarios_us_empresa_14f9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'rol'], name='usuarios_us_is_acti_597da1_idx'),
        ),
    ]
