# Generated by Django 6.0 on 2025-12-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('01', '01 - Gastos de Personal'), ('02', '02 - Gastos por Trabajos, Suministros y Servicios'), ('03', '03 - Arrendamientos'), ('04', '04 - Gastos de Activos Fijos'), ('05', '05 - Gastos de Representación'), ('06', '06 - Otras Deducciones Admitidas'), ('07', '07 - Gastos Financieros'), ('08', '08 - Gastos Extraordinarios'), ('09', '09 - Compras y Gastos que forman parte del Costo de Venta'), ('10', '10 - Adquisiciones de Activos'), ('11', '11 - Gastos de Seguros')], default='02', help_text='Tipo de Bienes y Servicios (DGII 606)', max_length=2)),
                ('fecha_compra', models.DateField(help_text='Fecha de la factura del proveedor')),
                ('numero_factura_proveedor', models.CharField(max_length=50)),
                ('numero_ncf', models.CharField(blank=True, help_text='Número de Comprobante Fiscal', max_length=20, null=True)),
                ('ncf_modificado', models.CharField(blank=True, help_text='NCF afectado por Nota de Crédito/Débito', max_length=20, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('CXP', 'En Cuentas por Pagar'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itbis_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itbis_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itbis_llevado_al_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isr_retenido', models.DecimalField(decimal_places=2, default=0, help_text='Retención de Renta', max_digits=14)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_linea', models.CharField(choices=[('ALMACENABLE', 'Inventario'), ('GASTO', 'Gasto Directo'), ('ACTIVO', 'Activo Fijo')], default='ALMACENABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_linea', models.CharField(choices=[('ALMACENABLE', 'Inventario'), ('GASTO', 'Gasto Directo'), ('ACTIVO', 'Activo Fijo')], default='ALMACENABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(help_text='Ej: Servicios Públicos, Nómina, Mantenimiento', max_length=100)),
                ('fecha_gasto', models.DateField()),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_ncf', models.CharField(blank=True, max_length=20, null=True)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('ENVIADA', 'Enviada al Proveedor'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA_TOTAL', 'Recibida Totalmente'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('condiciones_pago', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('detalles', models.TextField(help_text='Descripción de productos/servicios solicitados')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
            },
        ),
    ]
