# Generated by Django 5.2.7 on 2025-12-16 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_add_empresa_and_audit_fields'),
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        ('productos', '0002_alter_categoria_activa_alter_producto_activo_and_more'),
        ('proveedores', '0004_alter_proveedor_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha_gasto'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcotizacionproveedor',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Cotización', 'verbose_name_plural': 'Solicitudes de Cotización'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('CXP', 'En Cuentas por Pagar'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], db_index=True, default='REGISTRADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(db_index=True, help_text='Fecha de la factura del proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_factura_proveedor',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_gasto',
            field=models.CharField(choices=[('01', '01 - Gastos de Personal'), ('02', '02 - Gastos por Trabajos, Suministros y Servicios'), ('03', '03 - Arrendamientos'), ('04', '04 - Gastos de Activos Fijos'), ('05', '05 - Gastos de Representación'), ('06', '06 - Otras Deducciones Admitidas'), ('07', '07 - Gastos Financieros'), ('08', '08 - Gastos Extraordinarios'), ('09', '09 - Compras y Gastos que forman parte del Costo de Venta'), ('10', '10 - Adquisiciones de Activos'), ('11', '11 - Gastos de Seguros')], db_index=True, default='02', help_text='Tipo de Bienes y Servicios (DGII 606)', max_length=2),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(db_index=True, help_text='Ej: Servicios Públicos, Nómina, Mantenimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('ENVIADA', 'Enviada al Proveedor'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA_TOTAL', 'Recibida Totalmente'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacionproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'estado'], name='compras_com_empresa_1e2315_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor', 'estado'], name='compras_com_proveed_095ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'fecha_compra'], name='compras_com_empresa_ea207c_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado', '-fecha_registro'], name='compras_com_estado_55205e_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecompra',
            index=models.Index(fields=['compra', 'producto'], name='compras_det_compra__70eaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleordencompra',
            index=models.Index(fields=['orden', 'producto'], name='compras_det_orden_i_d18841_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', 'estado'], name='compras_gas_empresa_5d82e1_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', 'categoria'], name='compras_gas_empresa_03467d_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', 'fecha_gasto'], name='compras_gas_empresa_aa422b_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['estado', '-fecha_gasto'], name='compras_gas_estado_bce0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'estado'], name='compras_ord_empresa_40fd15_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'estado'], name='compras_ord_proveed_fa1819_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', '-fecha_emision'], name='compras_ord_estado_261bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacionproveedor',
            index=models.Index(fields=['empresa', 'estado'], name='compras_sol_empresa_990f88_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacionproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='compras_sol_proveed_a612c8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacionproveedor',
            index=models.Index(fields=['-fecha_solicitud'], name='compras_sol_fecha_s_5d0b6b_idx'),
        ),
    ]
