# Generated by Django 5.2.7 on 2025-12-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_add_retenciones_fiscales'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detalledevolucionproveedor',
            new_name='compras_det_devoluc_0a82ab_idx',
            old_name='compras_det_devoluc_j1k2l3_idx',
        ),
        migrations.RenameIndex(
            model_name='detallerecepcion',
            new_name='compras_det_recepci_ac2cb5_idx',
            old_name='compras_det_recepci_7a8b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='devolucionproveedor',
            new_name='compras_dev_empresa_375f0f_idx',
            old_name='compras_dev_empresa_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='devolucionproveedor',
            new_name='compras_dev_proveed_fed6ba_idx',
            old_name='compras_dev_proveed_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='devolucionproveedor',
            new_name='compras_dev_empresa_4c772a_idx',
            old_name='compras_dev_empresa_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='gastoimportacion',
            new_name='compras_gas_liquida_6a98d9_idx',
            old_name='compras_gas_liquida_v4w5x6_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionimportacion',
            new_name='compras_liq_empresa_140ff1_idx',
            old_name='compras_liq_empresa_m4n5o6_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionimportacion',
            new_name='compras_liq_compra__53964e_idx',
            old_name='compras_liq_compra_p7q8r9_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionimportacion',
            new_name='compras_liq_empresa_0578f5_idx',
            old_name='compras_liq_empresa_s1t2u3_idx',
        ),
        migrations.RenameIndex(
            model_name='recepcioncompra',
            new_name='compras_rec_empresa_69eb84_idx',
            old_name='compras_rec_empresa_7e8c7c_idx',
        ),
        migrations.RenameIndex(
            model_name='recepcioncompra',
            new_name='compras_rec_orden_c_971b28_idx',
            old_name='compras_rec_orden_c_a7e8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='recepcioncompra',
            new_name='compras_rec_empresa_20f0a1_idx',
            old_name='compras_rec_empresa_f1b3c2_idx',
        ),
        migrations.RenameIndex(
            model_name='retencioncompra',
            new_name='compras_ret_empresa_6876d6_idx',
            old_name='compras_ret_empresa_d8b3f5_idx',
        ),
        migrations.RenameIndex(
            model_name='retencioncompra',
            new_name='compras_ret_tipo_re_6b0b0d_idx',
            old_name='compras_ret_tipo_re_a1c4f2_idx',
        ),
    ]
