# Generated by Django 6.0 on 2025-12-18 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_alter_empresa_activo_alter_empresa_rnc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_fiscal', models.JSONField(default=dict, help_text='Configuración relacionada con DGII y aspectos fiscales', verbose_name='Configuración Fiscal')),
                ('config_facturacion', models.JSONField(default=dict, help_text='Plazos de crédito, descuentos, numeración, etc.', verbose_name='Configuración de Facturación')),
                ('config_inventario', models.JSONField(default=dict, help_text='Stock mínimo, método de costeo, alertas, etc.', verbose_name='Configuración de Inventario')),
                ('config_notificaciones', models.JSONField(default=dict, help_text='Emails automáticos, alertas, recordatorios', verbose_name='Configuración de Notificaciones')),
                ('config_reportes', models.JSONField(default=dict, help_text='Paginación, formatos de exportación, caché', verbose_name='Configuración de Reportes')),
                ('config_compras', models.JSONField(default=dict, help_text='Plazos de pago, aprobaciones, órdenes de compra', verbose_name='Configuración de Compras')),
                ('config_seguridad', models.JSONField(default=dict, help_text='Sesiones, contraseñas, intentos de login', verbose_name='Configuración de Seguridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresas',
                'permissions': [('view_config_fiscal', 'Puede ver configuración fiscal'), ('change_config_fiscal', 'Puede cambiar configuración fiscal'), ('view_config_facturacion', 'Puede ver configuración de facturación'), ('change_config_facturacion', 'Puede cambiar configuración de facturación'), ('view_config_inventario', 'Puede ver configuración de inventario'), ('change_config_inventario', 'Puede cambiar configuración de inventario'), ('view_config_notificaciones', 'Puede ver configuración de notificaciones'), ('change_config_notificaciones', 'Puede cambiar configuración de notificaciones'), ('view_config_reportes', 'Puede ver configuración de reportes'), ('change_config_reportes', 'Puede cambiar configuración de reportes'), ('view_config_compras', 'Puede ver configuración de compras'), ('change_config_compras', 'Puede cambiar configuración de compras'), ('view_config_seguridad', 'Puede ver configuración de seguridad'), ('change_config_seguridad', 'Puede cambiar configuración de seguridad'), ('restablecer_configuracion', 'Puede restablecer configuración a valores por defecto')],
            },
        ),
    ]
